// AUTO-GENERATED by scripts/gen-migrations.ts — do not edit by hand.
// Embeds drizzle-kit migrations so they ship inside the single binary (design 08).

export interface EmbeddedMigration {
  readonly tag: string
  readonly statements: ReadonlyArray<string>
}

export const migrations: ReadonlyArray<EmbeddedMigration> = [
  {
    "tag": "0000_init",
    "statements": [
      "CREATE TABLE \"access_tokens\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"service_id\" text NOT NULL,\n\t\"token_hash\" \"bytea\" NOT NULL,\n\t\"scope_key_ids\" jsonb NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"revoked_at\" timestamp with time zone,\n\t\"issued_ip\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"access_tokens_token_hash_unique\" UNIQUE(\"token_hash\")\n);",
      "CREATE TABLE \"audit_logs\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text NOT NULL,\n\t\"actor_type\" text NOT NULL,\n\t\"actor_id\" text,\n\t\"action\" text NOT NULL,\n\t\"environment_id\" text,\n\t\"target_type\" text,\n\t\"target_id\" text,\n\t\"metadata\" jsonb,\n\t\"ip\" text,\n\t\"user_agent\" text,\n\t\"result\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"challenges\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"service_id\" text NOT NULL,\n\t\"nonce\" \"bytea\" NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"consumed_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"environments\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"project_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"slug\" text NOT NULL,\n\t\"protected\" boolean DEFAULT false NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"grants\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"service_id\" text NOT NULL,\n\t\"key_id\" text NOT NULL,\n\t\"created_by\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"kek_versions\" (\n\t\"version\" integer PRIMARY KEY NOT NULL,\n\t\"fingerprint\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"key_versions\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"key_id\" text NOT NULL,\n\t\"version\" integer NOT NULL,\n\t\"plaintext\" text,\n\t\"ciphertext\" \"bytea\",\n\t\"nonce\" \"bytea\",\n\t\"wrapped_dek\" \"bytea\",\n\t\"dek_nonce\" \"bytea\",\n\t\"kek_version\" integer,\n\t\"aead\" text,\n\t\"created_by\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"keys\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"environment_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"type\" text NOT NULL,\n\t\"current_version\" integer DEFAULT 1 NOT NULL,\n\t\"description\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"memberships\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"role\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"organizations\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"slug\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"organizations_slug_unique\" UNIQUE(\"slug\")\n);",
      "CREATE TABLE \"projects\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"slug\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"services\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"environment_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"service_id\" text NOT NULL,\n\t\"public_key\" \"bytea\" NOT NULL,\n\t\"enc_public_key\" \"bytea\" NOT NULL,\n\t\"status\" text DEFAULT 'active' NOT NULL,\n\t\"ip_allowlist\" jsonb,\n\t\"last_auth_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"services_service_id_unique\" UNIQUE(\"service_id\")\n);",
      "CREATE TABLE \"sessions\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"token_hash\" \"bytea\" NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"sessions_token_hash_unique\" UNIQUE(\"token_hash\")\n);",
      "CREATE TABLE \"users\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"password_hash\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"users_email_unique\" UNIQUE(\"email\")\n);",
      "ALTER TABLE \"access_tokens\" ADD CONSTRAINT \"access_tokens_service_id_services_id_fk\" FOREIGN KEY (\"service_id\") REFERENCES \"public\".\"services\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"audit_logs\" ADD CONSTRAINT \"audit_logs_org_id_organizations_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"challenges\" ADD CONSTRAINT \"challenges_service_id_services_id_fk\" FOREIGN KEY (\"service_id\") REFERENCES \"public\".\"services\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"environments\" ADD CONSTRAINT \"environments_project_id_projects_id_fk\" FOREIGN KEY (\"project_id\") REFERENCES \"public\".\"projects\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"grants\" ADD CONSTRAINT \"grants_service_id_services_id_fk\" FOREIGN KEY (\"service_id\") REFERENCES \"public\".\"services\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"grants\" ADD CONSTRAINT \"grants_key_id_keys_id_fk\" FOREIGN KEY (\"key_id\") REFERENCES \"public\".\"keys\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"grants\" ADD CONSTRAINT \"grants_created_by_users_id_fk\" FOREIGN KEY (\"created_by\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE no action ON UPDATE no action;",
      "ALTER TABLE \"key_versions\" ADD CONSTRAINT \"key_versions_key_id_keys_id_fk\" FOREIGN KEY (\"key_id\") REFERENCES \"public\".\"keys\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"key_versions\" ADD CONSTRAINT \"key_versions_created_by_users_id_fk\" FOREIGN KEY (\"created_by\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE no action ON UPDATE no action;",
      "ALTER TABLE \"keys\" ADD CONSTRAINT \"keys_environment_id_environments_id_fk\" FOREIGN KEY (\"environment_id\") REFERENCES \"public\".\"environments\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"memberships\" ADD CONSTRAINT \"memberships_org_id_organizations_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"memberships\" ADD CONSTRAINT \"memberships_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"projects\" ADD CONSTRAINT \"projects_org_id_organizations_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"services\" ADD CONSTRAINT \"services_environment_id_environments_id_fk\" FOREIGN KEY (\"environment_id\") REFERENCES \"public\".\"environments\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"sessions\" ADD CONSTRAINT \"sessions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "CREATE INDEX \"access_tokens_service_idx\" ON \"access_tokens\" USING btree (\"service_id\");",
      "CREATE INDEX \"audit_org_time_idx\" ON \"audit_logs\" USING btree (\"org_id\",\"created_at\");",
      "CREATE INDEX \"audit_actor_idx\" ON \"audit_logs\" USING btree (\"actor_type\",\"actor_id\");",
      "CREATE INDEX \"challenges_service_exp_idx\" ON \"challenges\" USING btree (\"service_id\",\"expires_at\");",
      "CREATE UNIQUE INDEX \"environments_project_slug_uq\" ON \"environments\" USING btree (\"project_id\",\"slug\");",
      "CREATE UNIQUE INDEX \"grants_service_key_uq\" ON \"grants\" USING btree (\"service_id\",\"key_id\");",
      "CREATE INDEX \"grants_service_idx\" ON \"grants\" USING btree (\"service_id\");",
      "CREATE INDEX \"grants_key_idx\" ON \"grants\" USING btree (\"key_id\");",
      "CREATE UNIQUE INDEX \"key_versions_key_version_uq\" ON \"key_versions\" USING btree (\"key_id\",\"version\");",
      "CREATE INDEX \"key_versions_key_idx\" ON \"key_versions\" USING btree (\"key_id\");",
      "CREATE UNIQUE INDEX \"keys_env_name_uq\" ON \"keys\" USING btree (\"environment_id\",\"name\");",
      "CREATE UNIQUE INDEX \"memberships_org_user_uq\" ON \"memberships\" USING btree (\"org_id\",\"user_id\");",
      "CREATE UNIQUE INDEX \"projects_org_slug_uq\" ON \"projects\" USING btree (\"org_id\",\"slug\");"
    ]
  },
  {
    "tag": "0001_sweep_indexes",
    "statements": [
      "CREATE INDEX \"access_tokens_exp_idx\" ON \"access_tokens\" USING btree (\"expires_at\");",
      "CREATE INDEX \"challenges_exp_idx\" ON \"challenges\" USING btree (\"expires_at\");",
      "CREATE INDEX \"sessions_exp_idx\" ON \"sessions\" USING btree (\"expires_at\");"
    ]
  }
]
