// AUTO-GENERATED by scripts/gen-assets.ts — do not edit by hand.
// Embeds the built dashboard SPA so it ships inside the single binary (design 08).
// Empty until `bun run build:web` + `bun run scripts/gen-assets.ts` are run.

export interface EmbeddedAsset {
  readonly contentType: string
  readonly base64: string
}

export const assets: Record<string, EmbeddedAsset> = {}
