// AUTO-GENERATED by scripts/gen-assets.ts — do not edit by hand.
// Embeds the built dashboard SPA so it ships inside the single binary (design 08).

export interface EmbeddedAsset {
  readonly contentType: string
  readonly base64: string
}

export const assets: Record<string, EmbeddedAsset> = {}
