/**
 * Bundles the built dashboard SPA (src/http/assets) into src/http/assets.gen.ts so it ships
 * inside the compiled single binary (design 08). Run after `bun run build:web`.
 *
 *   bun run scripts/gen-assets.ts
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs"
import { join, relative } from "node:path"

const ASSETS_DIR = join(import.meta.dir, "..", "src", "http", "assets")
const OUT = join(import.meta.dir, "..", "src", "http", "assets.gen.ts")

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".map": "application/json",
}

const walk = (dir: string): string[] => {
  const out: string[] = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) out.push(...walk(full))
    else out.push(full)
  }
  return out
}

const entries: Record<string, { contentType: string; base64: string }> = {}
if (existsSync(ASSETS_DIR)) {
  for (const file of walk(ASSETS_DIR)) {
    const rel = "/" + relative(ASSETS_DIR, file).split("\\").join("/")
    const ext = rel.slice(rel.lastIndexOf("."))
    entries[rel] = {
      contentType: CONTENT_TYPES[ext] ?? "application/octet-stream",
      base64: readFileSync(file).toString("base64"),
    }
  }
}

const body = `// AUTO-GENERATED by scripts/gen-assets.ts — do not edit by hand.
// Embeds the built dashboard SPA so it ships inside the single binary (design 08).

export interface EmbeddedAsset {
  readonly contentType: string
  readonly base64: string
}

export const assets: Record<string, EmbeddedAsset> = ${JSON.stringify(entries)}
`
writeFileSync(OUT, body)
console.log(`Wrote ${OUT} with ${Object.keys(entries).length} asset(s).`)
