/**
 * Bundles the drizzle-kit migration output into a TS module (`src/db/migrations.gen.ts`)
 * so migrations are embedded in the compiled single binary (design 08) — the binary has no
 * migrations folder on disk. Re-run after generating a new migration; commit the output.
 *
 *   bun run scripts/gen-migrations.ts
 */
import { readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const MIG_DIR = join(import.meta.dir, "..", "src", "db", "migrations")
const OUT = join(import.meta.dir, "..", "src", "db", "migrations.gen.ts")

interface JournalEntry {
  idx: number
  tag: string
}

const journal = JSON.parse(readFileSync(join(MIG_DIR, "meta", "_journal.json"), "utf8")) as {
  entries: JournalEntry[]
}

const entries = [...journal.entries].sort((a, b) => a.idx - b.idx)

const migrations = entries.map((e) => {
  const sql = readFileSync(join(MIG_DIR, `${e.tag}.sql`), "utf8")
  const statements = sql
    .split("--> statement-breakpoint")
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
  return { tag: e.tag, statements }
})

const body = `// AUTO-GENERATED by scripts/gen-migrations.ts — do not edit by hand.
// Embeds drizzle-kit migrations so they ship inside the single binary (design 08).

export interface EmbeddedMigration {
  readonly tag: string
  readonly statements: ReadonlyArray<string>
}

export const migrations: ReadonlyArray<EmbeddedMigration> = ${JSON.stringify(migrations, null, 2)}
`

writeFileSync(OUT, body)
console.log(`Wrote ${OUT} with ${migrations.length} migration(s), ${migrations.reduce((n, m) => n + m.statements.length, 0)} statements.`)
